Finished the majority of assignment breakdown page and file upload
cjohnson74/SWE-project pull request #50
Opened 2024-11-23 10:11 UTC by cjohnson74

Still needs a few more manual tests.

2024-11-23 15:31 UTC, ShringariV requested changes
Failed some of the sonar-checks, just go through them

2024-11-23 21:46 UTC, radliff submitted a review, later dismissed

2024-11-23 22:48 UTC, MatthewMilez submitted a review, later dismissed

2024-11-26 19:53 UTC, radliff approved these changes

2024-11-26 20:34 UTC, MatthewMilez approved these changes

2024-12-03 21:54 UTC, merged